site_name: LIRE Documentation
site_url: http://www.semanticmetadata.net
copyright: Copyright &copy; 2015, Mathias Lux.
google_analytics: ['UA-576792-1', 'auto']
pages:
- [index.md, Home]
- [lirefaq.md, FAQ]
- [createindex.md, Basics, Create Index]
- [searchindex.md, Basics, Search]
- [bovw.md, Advanced, Bag of Visual Words]
- [simple.md, Advanced, SIMPLE Local Features]
- [autocolorcorrelation.md, Advanced, AutoColorCorrelogram]
- [applyfilters.md, Advanced, Applying Filters]
- [lireinternals.md, Other, LIRE Internals]
- [imageread.md, Other, Image Handling]

